#!/usr/bin/env bash
# Tarefa 4: Início no estado de 18/10 (fascículo em breve, sem gráfico, sem evento até a Tarefa 9).
source "$(dirname "$0")/lib.sh"
tem index.html '<h1 class="abertura__titulo" id="abertura-titulo">A conjuntura brasileira, explicada pela teoria\.</h1>' "I1 frase"
tem index.html 'Somos a Liga Acadêmica de Macroeconomia da UFRGS\. Buscamos promover o ensino e o debate da macroeconomia e seus impactos\.' "I1 subtítulo"
tem index.html "<a class=\"botao\" href=\"#fasciculo\">Ver os textos do ${NO}1</a>" "I1 botão antes do lançamento"
tem index.html 'href="#como-funcionamos">Ver como funcionamos' "I1 segundo botão"
conta index.html 'class="mapa-ponto"' 175 "175 pontos do logo"
conta index.html 'class="mapa-destaque"' 1 "um ponto vermelho (Porto Alegre)"
tem index.html 'id="fasciculo"' "âncora do I2"
tem index.html "Fascículo ${NO}1: em breve" "I2 em breve"
tem index.html 'O primeiro fascículo está em produção\.' "I2 texto do em breve"
tem index.html 'Endividamento das famílias e financeirização no Brasil' "I2 lista: Pedone"
tem index.html 'Subdesenvolvimento: uma visão schumpeteriana' "I2 lista: Pittella"
tem index.html 'Seguir @macroliga\.ufrgs para saber do lançamento' "I2 botão Seguir"
tem index.html 'id="i2-fasciculo"[^>]*hidden' "I2 publicado oculto"
tem index.html 'Nenhum evento agendado\.' "I4 estado vazio"
tem index.html 'Todo texto passa pelas mesmas quatro etapas' "I5 título"
conta index.html 'class="etapa( |")' 4 "I5 quatro etapas"
conta index.html 'etapa--publicacao' 1 "I5 etapa Publicação marcada"
tem index.html 'Ler sobre a liga' "I5 botão"
tem index.html 'Seguir no Instagram' "I6 Instagram"
tem index.html 'Seguir no LinkedIn' "I6 LinkedIn"
nao_tem index.html 'id="i3"' "I3 ausente até a Tarefa 15 (D1)"
corpo_nao_tem index.html 'nº [0-9]' "nenhum nº separado do número"
fim
